/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project252;

/**
 *
 * @author Lenovo
 */
public class signupGUI extends javax.swing.JFrame {

    boolean flag;

    public signupGUI() {
        initComponents();
        login.setContentAreaFilled(false);
        login.setOpaque(false);
        signup.setContentAreaFilled(false);
        signup.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameSpace = new javax.swing.JTextField();
        passwordfield2 = new javax.swing.JTextField();
        passwordfield = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        usernameText = new javax.swing.JLabel();
        passwordText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        haveaccounttext = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        signupBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameSpaceActionPerformed(evt);
            }
        });
        jPanel1.add(nameSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 310, 40));
        jPanel1.add(passwordfield2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, 310, 40));
        jPanel1.add(passwordfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 310, 40));

        signup.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        signup.setText("signup");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        jPanel1.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 700, 240, 110));

        usernameText.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        usernameText.setText("User name");
        jPanel1.add(usernameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, -1, -1));

        passwordText.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        passwordText.setText("Password");
        jPanel1.add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Password Conformation");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, -1, -1));

        haveaccounttext.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        haveaccounttext.setText("Have an account?");
        jPanel1.add(haveaccounttext, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 830, -1, -1));

        login.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 102, 102));
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 830, -1, 30));

        signupBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/signup (3).png"))); // NOI18N
        signupBackground.setText("jLabel1");
        jPanel1.add(signupBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1350, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed

        String name = nameSpace.getText();
        String password = passwordfield.getText();
        String password2 = passwordfield2.getText();
        signup signupOb = new signup();
        boolean flag = signupOb.isValid(name, password, password2);
        if (flag) {
            //open home page and close this page 
            HomeGUI homePage = new HomeGUI();
            this.show(false);
            homePage.show(true);

        }


    }//GEN-LAST:event_signupActionPerformed


    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        loginGUI loginPage = new loginGUI();
        this.show(false);
        loginPage.show(true);

    }//GEN-LAST:event_loginActionPerformed

    private void nameSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameSpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameSpaceActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel haveaccounttext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JTextField nameSpace;
    private javax.swing.JLabel passwordText;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JTextField passwordfield2;
    private javax.swing.JButton signup;
    private javax.swing.JLabel signupBackground;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
